services:
  - type: web
    name: web-bias-news
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web_bias:app --bind 0.0.0.0:$PORT
    autoDeploy: true
